### PR TITLE
Retire @tbg

### PR DESCRIPTION
**Pull request by tbg**
I am on leave starting July 31.

### CODE REVIEW

**Comment by ahrtr** [comment]
@tbg Just as I mentioned previously, you don't have to retire yourself, as long as you will come back eventually (e.g 1 year later), and possibly [optional] keep the minimum activity before you come back.

Your expertise on raft really matter to the community.

But of course, it's all up to you.

**Comment by tbg** [comment]
I'd like to retire, just to come back to a clean slate. Though I'm not necessarily angling for dramatic change, I don't think I will pick up exactly where I left off after the break. Either way, in all likelihood I'll be "around"!

**Comment by ahrtr** [comment]
OK. Thank you for your leadership and great contributions on raft, and I wish you all the best!

One minor comment, could you add one more section "Emeritus Maintainer" in the same file, and add yourself under the section? When you decide to come back one day, you just need to raise a PR to request to rejoin.

**Review by ahrtr — APPROVED** [review]
cc @mitake @ptabor @serathius @spzala @wenjiaswe for awareness

**Comment by tbg** [comment]
Thank you!

**Pull request merged**
