### PR TITLE
WIP:standalone raftexample

### LINKED ISSUE #2: Implement a self-contained raft example
Refer to [raftexample](https://github.com/etcd-io/etcd/tree/main/contrib/raftexample) . But this example should **NOT** depend on etcd at all.

cc @Elbehery

### PR DESCRIPTION
**Pull request by Elbehery**
Signed-off-by: Mustafa Elbehery <melbeher@redhat.com>

resolves #2 

This PR contains only https://github.com/etcd-io/etcd/tree/main/contrib/raftexample files 

I try to use go modules, but I have issue vendoring `wal` from etcd repo

cc @ahrtr @spzala

### CODE REVIEW

**Comment by Elbehery** [comment]
I have this error while vendoring

```
go: module go.etcd.io/etcd/server/v3@upgrade found (v3.5.7), but does not contain package go.etcd.io/etcd/server/v3/storage/wal

go: module go.etcd.io/etcd/server/v3@upgrade found (v3.5.7), but does not contain package go.etcd.io/etcd/server/v3/storage/wal/walpb

```

```
go mod tidy
go: finding module for package go.etcd.io/etcd/server/v3/storage/wal/walpb
go: finding module for package go.etcd.io/etcd/server/v3/storage/wal
go.etcd.io/raft/v3/raftexample imports
	go.etcd.io/etcd/server/v3/storage/wal: module go.etcd.io/etcd/server/v3@latest found (v3.5.7), but does not contain package go.etcd.io/etcd/server/v3/storage/wal
go.etcd.io/raft/v3/raftexample imports
	go.etcd.io/etcd/server/v3/storage/wal/walpb: module go.etcd.io/etcd/server/v3@latest found (v3.5.7), but does not contain package go.etcd.io/etcd/server/v3/storage/wal/walpb

```

**Comment by Elbehery** [comment]
I fixed the vendoring errors 

Now there is another issue, the code in `raft.go` within `raft` repo uses `snapshotter` which is a dependency from etcd, and it uses types from etcd repo 

This func call [here](https://github.com/etcd-io/raft/blob/4566d8026beee544d684f12152e3f08aebe818f3/raftexample/raft.go#L126) from raft repo, uses this [type](https://github.com/etcd-io/raft/blob/4566d8026beee544d684f12152e3f08aebe818f3/vendor/go.etcd.io/etcd/server/v3/etcdserver/api/snap/snapshotter.go#L68) from etcd  


I am stuck :/

**Comment by Elbehery** [comment]
@serathius  hello ✋🏽  

I am sorry to cite you again about that :), i am just stuck with this 

maybe if the refactoring PR from https://github.com/etcd-io/etcd/pull/15471 is merged,  it is better ?

**Comment by ahrtr** [comment]
@Elbehery I see that you created two PRs: #40 and #41. can you close one of them? 

Please note that the raft example shouldn't depend on etcd at all. Also please remove the vendor directory.

**Comment by Elbehery** [comment]
thanks @ahrtr 

So i moved the raft example to this repo, but the dependencies are needed by the example, how can I move it here ? 

I tried to move the minimal code needed

**Comment by ahrtr** [comment]
> So i moved the raft example to this repo

It isn't correct. The original raftexample is just for your reference. You need to create a new self-contained example, which shouldn't depend on etcd at all.

**Comment by Elbehery** [comment]
Ok, now it makes sense to me .. I apologise for not understanding fully since the beginning .. 

Is it possible to move https://github.com/etcd-io/etcd/pull/15471 forward, because using interfaces could make it simpler ?

**Comment by Elbehery** [comment]
thanks a lot for your clarification 🙏🏽

**Pull request closed without merging**
