### PR TITLE
Refactoring on raft

### PR DESCRIPTION
**Pull request by ahrtr**
1. Renamed module name from `go.etcd.io/etcd/raft` to `go.etcd.io/raft`;
2. Updated the OWNER file;
3. Added .gitignore file;
4. Setup initial github workflow

### CODE REVIEW

**Comment by ahrtr** [comment]
Please review this PR commit by commit. The last commit (setting up github workflow) is basically coming from etcd.

cc @ptabor @serathius @spzala @tbg

**Review by serathius — APPROVED** [review]
LGTM
One question, why runners didn't test the PR?

**Comment by ahrtr** [comment]
> LGTM One question, why runners didn't test the PR?

Good question, it might be because it's the very first PR.

**Comment by ahrtr** [comment]
Thanks both @serathius and @tbg for the quick review. 

I will introduce more verification & protoc generation script in following PR.

**Comment by tbg** [comment]
> LGTM One question, why runners didn't test the PR?

I'm also not sure, but maybe GH actions only uses actions that are present on the merge-base, as opening a PR is a relatively low-privilege operation.

**Comment by ahrtr** [comment]
> > LGTM One question, why runners didn't test the PR?
> 
> I'm also not sure, but maybe GH actions only uses actions that are present on the merge-base, as opening a PR is a relatively low-privilege operation.

Let me follow this after merging this PR.

**Comment by serathius** [comment]
ok, we have some runs https://github.com/etcd-io/raft/actions

It was surprizing to me as fact that action is just introduced in the PR should not prevent it from being run. Possibly actions don't work on new repo.

**Pull request merged**
